name: Deploy Next.js applications

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t cs203someshit/tournax-frontend .
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Publish image to docker hub
        run: docker push cs203someshit/tournax-frontend:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull cs203someshit/tournax-frontend:latest
      - name: Stop previous process
        run: docker stop nextjs-app-container
      - name: Delete old container
        run: docker rmi nextjs-app-container
      - name: Run docker container
        run: docker run -d -p 80:3000 --name nextjs-app-container cs203someshit/tournax-frontend
