name: Deploy Next.js applications

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t cs203someshit/tournax-frontend:${{ github.sha }} .
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Publish image to docker hub
        run: docker push cs203someshit/tournax-frontend:${{ github.sha }}
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull cs203someshit/tournax-frontend:${{ github.sha }}
      - name: Stop and remove existing container (if running)
        run: |
          docker stop nextjs-app-container || true
          docker rm nextjs-app-container || true
      - name: Run docker container
        run: docker run -d -p 80:3000 --name nextjs-app-container cs203someshit/tournax-frontend:${{ github.sha }}
